{application,couchbeam,
             [{description,"Erlang CouchDB client"},
              {vsn,"1.7.1"},
              {modules,[couchbeam,couchbeam_app,couchbeam_attachments,
                        couchbeam_changes,couchbeam_changes_stream,
                        couchbeam_changes_sup,couchbeam_doc,couchbeam_ejson,
                        couchbeam_httpc,couchbeam_sup,couchbeam_util,
                        couchbeam_uuids,couchbeam_view,couchbeam_view_stream,
                        couchbeam_view_sup,gen_changes]},
              {registered,[couchbeam_sup]},
              {applications,[kernel,stdlib,asn1,crypto,public_key,ssl,idna,
                             hackney]},
              {included_applications,[]},
              {env,[]},
              {mod,{couchbeam_app,[]}},
              {maintainers,["Benoit Chesneau"]},
              {licenses,["MIT"]},
              {links,[{"Github","https://github.com/benoitc/couchbeam"}]},
              {files,["src","include","rebar.config","rebar.lock","README.md",
                      "NEWS.md","LICENSE","NOTICE"]}]}.
